[package]
name = "oxidized-transformers"
description = "Transformers library (not functional yet)"
version = "0.1.0"
edition = "2021"
license = "MIT"
homepage = "https://github.com/danieldk/oxidized-transformers"

[dependencies]
accelerate-src = { workspace = true, optional = true }
candle-core = { workspace = true }
candle-nn = { workspace = true }
hf-hub = { workspace = true }
regex = { workspace = true }
snafu = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokenizers = { workspace = true, features = ["http"] }

[dev-dependencies]
approx = { workspace = true }
rstest = { workspace = true }
ndarray = { workspace = true, features = ["approx-0_5"] }
rand_pcg = { workspace = true }
rand_core = { workspace = true }

[features]
accelerate = ["candle-core/accelerate", "candle-nn/accelerate"]
cuda = ["candle-core/cuda", "candle-nn/cuda"]
cudnn = ["candle-core/cudnn"]
metal = ["candle-core/metal", "candle-nn/metal"]